import httpx2

from esi_examples.models.auth import OauthTokenTD


def request_token(
    client_id: str,
    authorization_code: str,
    code_verifier: str,
    token_endpoint: str,
    user_agent: str,
) -> OauthTokenTD:
    """Takes an authorization code and code verifier and exchanges it for an access token and refresh token."""
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "grant_type": "authorization_code",
        "code": authorization_code,
        "client_id": client_id,
        "code_verifier": code_verifier,
    }
    response = httpx2.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = response.json()

    return result


def refresh_token(
    refresh_token: str,
    client_id: str,
    token_endpoint: str,
    user_agent: str,
) -> OauthTokenTD:
    """Takes a refresh token and exchanges it for a new oauth token."""
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "client_id": client_id,
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }
    response = httpx2.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = response.json()
    return result


async def async_request_token(
    client_id: str,
    authorization_code: str,
    code_verifier: str,
    token_endpoint: str,
    user_agent: str,
    client_session: httpx2.AsyncClient,
) -> OauthTokenTD:
    """Takes an authorization code and code verifier and exchanges it for an access token and refresh token.

    Args:
        client_id: The client ID of the application.
        authorization_code: The authorization code received from the SSO.
        code_verifier: The code verifier used to generate the code challenge, as generated by `generate_code_challenge`.
        token_endpoint: The token endpoint URI for exchanging the authorization code.
        user_agent: The User-Agent string to use in the request.
        client_session: The httpx2.AsyncClient session for making requests.

    Returns:
        A dictionary containing the access token and refresh token.

    Raises:
        ValueError: If client_session is not initialized.
        httpx2.HTTPStatusError: If the token request fails.
    """
    if not client_session:
        raise ValueError("client_session must be initialized to request token.")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "grant_type": "authorization_code",
        "code": authorization_code,
        "client_id": client_id,
        "code_verifier": code_verifier,
    }
    response = await client_session.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = await response.json()

    return result


async def async_refresh_token(
    refresh_token: str,
    client_id: str,
    token_endpoint: str,
    user_agent: str,
    client_session: httpx2.AsyncClient,
) -> OauthTokenTD:
    """Takes a refresh token and exchanges it for a new oauth token.

    Args:
        refresh_token: The refresh token portion of the OAuth2 token.
        client_id: The client ID of the application.
        token_endpoint: The token endpoint URI for refreshing tokens.
        user_agent: The User-Agent string to use in the request.
        client_session: The httpx2.AsyncClient session for making requests.

    Returns:
        A dictionary containing the new access token and refresh token.

    Raises:
        ValueError: If client_session is not initialized.
        httpx2.HTTPStatusError: If the token request fails.
    """
    if not client_session:
        raise ValueError("client_session must be initialized to refresh token.")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "client_id": client_id,
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }
    response = await client_session.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = await response.json()
    return result
